import type { NextPage } from 'next'
import Head from 'next/head'
import ButtonSwitchTheme from '../components/buttonSwitchTheme'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className='flex px-4'>
        <h1>Logo</h1>
        <div className="ml-auto">
          <a href="/" className="font-bold text-blue-500 capitalize">Home</a>
        </div>
      </nav>
    </>

      
  )
}

export default Home
