import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { Card, Dropdown } from '../components'

const Home: NextPage = () => {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <nav className="nav">
        <div className="container flex-row-center justify-between">
          <img src="/icons/InPOSery.svg" alt="logo" className='logo'/>
          <div className="nav-links">
            <Link href=""><a className="nav-item">Home</a></Link>
            <Link href=""><a className="nav-item">Feature</a></Link>
            <Link href=""><a className="nav-item">Review</a></Link>
            <Link href=""><a className="nav-item">Pricing</a></Link>
          </div>
          <Link href=""><a className='btn btn-link'>Masuk</a></Link>
        </div>
      </nav>
      <header>
        <div className="container flex-row-center">
          <div className='header-text'>
            <h1 className='title'>Manage Your <span className="text-blue-primer">Store Sales</span> and <span className="text-blue-primer">Revenue</span> Easily</h1>
            <p className='subtitle'>We offer the convenience of your POS System. with various mainstay features such as calculating daily sales, setting roles, inventory management, daily, monthly, weekly transactions in your store.</p>
            <button className="btn-big btn-link mx-auto">GET STARTED</button>
            <Link href=""><a>Subscribe from IDR 80k/month</a></Link>
          </div>
          <div className="header-art">
            <img src="/images/vector_ilustration1.svg" alt="Ilustration 1 BG" id="vector-ilustration1"/>
            <img src="/images/ilustration1.svg" alt="Ilustration 1" id="ilustration1"/>
          </div>
        </div>
      </header>
      <section className='feature relative'>
        <img src="/images/Eclipse.svg" alt="Eclipse" className='eclipse eclipse1'/>
        <img src="/images/Eclipse.svg" alt="Eclipse" className='eclipse eclipse2'/>
        <div className="container">
          <h1 className='feature-title'>WE PROVIDE YOU<span className='longbox mx-auto'></span></h1>
          <p className="feature-subtitle">Some of the features that we provide to your store, to support ease of transactions and calculation of your sales</p>
          <div className="feature-grid">
            <Card icon="/icons/facebook.svg" title="Dailyt Transaction" subtitle="View daily transaction information." />
            <Card icon="/icons/facebook.svg" title="Dailyt Transaction" subtitle="View daily transaction information." />
            <Card icon="/icons/facebook.svg" title="Dailyt Transaction" subtitle="View daily transaction information." />
            <Card icon="/icons/facebook.svg" title="Dailyt Transaction" subtitle="View daily transaction information." />
            <Card icon="/icons/facebook.svg" title="Dailyt Transaction" subtitle="View daily transaction information." />
            <Card icon="/icons/facebook.svg" title="Dailyt Transaction" subtitle="View daily transaction information." />
          </div>
        </div>
      </section>
      <section className='benefits'>
        <div className="container flex-row-center justify-strecth">
          <img src="/images/ilustration2.svg" alt="Ilustration 2" className='ilustration2'/>
          <div className="benefits-card">
            <h1>Busines Advantage Using</h1>
            <h1 className='text-blue-primer'>POS System</h1>
            <ul>
              <li>Regular business finance management.</li>
              <li>Information about sales/profit is more systematic.</li>
              <li>Organized business financial management</li>
            </ul>
          </div>
        </div>
      </section>
      <section className="faq">
        <div className="container flex-row-center justify-between">
          <div className="faq-wrapper">
            <h1 className="faq-title">Frequently Ask Question (F.A.Q)</h1>
            <ul className="faq-ul">
              <Dropdown question='How long can I use the free trial available?' answer='Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae, rem eos, quaerat ut dignissimos ipsa commodi doloribus excepturi vero quam reiciendis, saepe id nobis natus dolore fugit ducimus debitis architecto!'/>
              <Dropdown question='Can I upload anything I want on there?'answer='Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae, rem eos, quaerat ut dignissimos ipsa commodi doloribus excepturi vero quam reiciendis, saepe id nobis natus dolore fugit ducimus debitis architecto! '/>
              <Dropdown question='How many shops can I create in once'answer='Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae, rem eos, quaerat ut dignissimos ipsa commodi doloribus excepturi vero quam reiciendis, saepe id nobis natus dolore fugit ducimus debitis architecto!'/>
              <Dropdown question='How many shops can I create in once'answer='Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae, rem eos, quaerat ut dignissimos ipsa commodi doloribus excepturi vero quam reiciendis, saepe id nobis natus dolore fugit ducimus debitis architecto!'/>
            </ul>
          </div>
          <img src="/images/ilustration3.svg" alt="Ilustration 3" className='ilustration3' />
        </div>
      </section>
      <section className="plans">
        <div className="container">
          <h1 className="plans-title">15 - days free trial.</h1>
          <p className="plans-subtitle">Try Our POS System for free</p>
          <div className="plans-wraper">
            <div className="plan-card">
              <div className="plan-title">Monthly</div>
              <ul className="plan-features">
                <li className="plan-feature">Lorem ipsum dolor sit amet.</li>
                <li className="plan-feature">Lorem ipsum dolor sit amet.</li>
                <li className="plan-feature">Lorem ipsum dolor sit amet.</li>
                <li className="plan-feature">Lorem ipsum dolor sit amet.</li>
                <li className="plan-feature">Lorem ipsum dolor sit amet.</li>
              </ul>
              <p className="plan-price">Rp.<span>123</span>/month</p>
              <button className="btn btn-link">Choose</button>
            </div>
            <div className="plan-card plan-card-recomend">
              <div className="plan-title">Monthly</div>
              <ul className="plan-features">
                <li className="plan-feature">Lorem ipsum dolor sit amet.</li>
                <li className="plan-feature">Lorem ipsum dolor sit amet.</li>
                <li className="plan-feature">Lorem ipsum dolor sit amet.</li>
                <li className="plan-feature">Lorem ipsum dolor sit amet.</li>
                <li className="plan-feature">Lorem ipsum dolor sit amet.</li>
              </ul>
              <p className="plan-price">Rp.<span>123</span>/month</p>
              <button className="btn btn-link">Choose</button>
            </div>
            <div className="plan-card">
              <div className="plan-title">Monthly</div>
              <ul className="plan-features">
                <li className="plan-feature">Lorem ipsum dolor sit amet.</li>
                <li className="plan-feature">Lorem ipsum dolor sit amet.</li>
                <li className="plan-feature">Lorem ipsum dolor sit amet.</li>
                <li className="plan-feature">Lorem ipsum dolor sit amet.</li>
                <li className="plan-feature">Lorem ipsum dolor sit amet.</li>
              </ul>
              <p className="plan-price">Rp.<span>123</span>/month</p>
              <button className="btn btn-link mx-auto">Choose</button>
            </div>
          </div>
        </div>
      </section>
      <section className="review">
        <img src="/images/Eclipse.svg" alt="Eclipse" className='eclipse eclipse1'/>
        <img src="/images/Eclipse.svg" alt="Eclipse" className='eclipse eclipse2'/>
        <div className="review-text">
          <h1 className="review-title">What Our <span>Customer Are Saying</span></h1>
          <p className="review-subtitle">Our customer love it about POS system to engage their bussiness
          and help them to get efficiency when calculate their revenue</p>
        </div>
        <div className="review-wraper">
          <div className="review-card">
            <div className="review-img"></div>
            <div className="reviewer">Lorem, ipsum.</div>
            <div className="flex-row-center justify-between">
              <div className="reviewer-job">Lorem, ipsum dolor.</div>
              <div className="ratings">1 2 3 4 5</div>
            </div>
            <div className="reviewer-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id officiis recusandae, quibusdam veritatis excepturi earum ab nam quis minus beatae?</div>
          </div>
          <div className="review-card">
            <div className="review-img"></div>
            <div className="reviewer">Lorem, ipsum.</div>
            <div className="flex-row-center justify-between">
              <div className="reviewer-job">Lorem, ipsum dolor.</div>
              <div className="ratings">1 2 3 4 5</div>
            </div>
            <div className="reviewer-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id officiis recusandae, quibusdam veritatis excepturi earum ab nam quis minus beatae?</div>
          </div>
          <div className="review-card">
            <div className="review-img"></div>
            <div className="reviewer">Lorem, ipsum.</div>
            <div className="flex-row-center justify-between">
              <div className="reviewer-job">Lorem, ipsum dolor.</div>
              <div className="ratings">1 2 3 4 5</div>
            </div>
            <div className="reviewer-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id officiis recusandae, quibusdam veritatis excepturi earum ab nam quis minus beatae?</div>
          </div>
          <div className="review-card">
            <div className="review-img"></div>
            <div className="reviewer">Lorem, ipsum.</div>
            <div className="flex-row-center justify-between">
              <div className="reviewer-job">Lorem, ipsum dolor.</div>
              <div className="ratings">1 2 3 4 5</div>
            </div>
            <div className="reviewer-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id officiis recusandae, quibusdam veritatis excepturi earum ab nam quis minus beatae?</div>
          </div>
          <div className="review-card">
            <div className="review-img"></div>
            <div className="reviewer">Lorem, ipsum.</div>
            <div className="flex-row-center justify-between">
              <div className="reviewer-job">Lorem, ipsum dolor.</div>
              <div className="ratings">1 2 3 4 5</div>
            </div>
            <div className="reviewer-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id officiis recusandae, quibusdam veritatis excepturi earum ab nam quis minus beatae?</div>
          </div>
        </div>
        <div className="review-control">
          <img src="/icons/BigRightArrowDead.svg" alt="Left Arrow" className='prev'/>
          <img src="/icons/BigRightArrow.svg" alt="Right Arrow" className='next'/>
        </div>
      </section>
      <section className="mobile">
        <div className="container">
          <div className="mobile-wraper">
            <h1 className="mobile-title">Manage your Transactions through the <span>Mobile application </span>and view the Dashboard through the <span>Website</span></h1>
            <p className="mobile-subtitle">Download the app to manage your projects, keep track of the progress and complete tasks without procastinating. Stay on track and complete on time!</p>
          </div>
        </div>
        <img src="/images/PhoneMockup.png" alt="Mobile" className='mobile-img-1'/>
        <img src="/images/PhoneMockup.png" alt="Mobile" className='mobile-img-2'/>
      </section>
      <section className="prefooter">
        <div className="container">
          <img src="/icons/InPOSery.svg" alt="Logo" width={100}/>
          <div className="prefooter-text">
            <p>Download Now</p>
            <p>License</p>
          </div>
          <div className="prefooter-nav">
            <Link href=""><a className="preefooter-nav-item">Home</a></Link>
            <Link href=""><a className="preefooter-nav-item">Feature</a></Link>
            <Link href=""><a className="preefooter-nav-item">Review</a></Link>
            <Link href=""><a className="preefooter-nav-item">Pricing</a></Link>
          </div>
        </div>
      </section>
      <footer>
        <div className="container relative">
          <p className="footer-text">© 2021 Inposery. All rights reserved</p>
          <div className="footer-sosmed">
            <Link href=""><img src="/icons/facebook.svg" alt="Facebook" /></Link>
            <Link href=""><img src="/icons/twitter.svg" alt="Tweeter" /></Link>
            <Link href=""><img src="/icons/instagram.svg" alt="Instagram" /></Link>
          </div>
        </div>
      </footer>
    </>

      
  )
}

export default Home
