import type { NextPage } from 'next'
import Head from 'next/head'
import {Counter} from '../components'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Counter />
      <Counter defaultValue={100}/>
    </>

      
  )
}

export default Home
