# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development Flow

on:
  push:
    branches: ["develop"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install dependecies
        run: npm ci

      - name: Build App
        run: npm run build

      - name: Export App
        run: npm run export

      - name: Copy files via SCP to VPS
        uses: appleboy/scp-action@master
        with:
          host: 103.183.75.5
          username: inposery
          password: Inposery2022
          port: 22
          source: out
          target: /var/www/inposery
          strip_components: 1
